---
title: "fitbit-analysis"
author: "Shelby Sturrock"
date: "14/01/2022"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE, results=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
knitr::opts_knit$set(root.dir = '~/Desktop/CSEP fitbit')
```

## processing FitBit data 

### read in data from three time periods: 

```{r, results="hide"}

  # nov 08 - nov 21
    nov08<-list.files("fitbit_data/nov08-nov21", pattern="*.csv", full.names=TRUE)
    nov08_csv<-lapply(nov08, read.csv)
    names(nov08_csv)<-paste(gsub("fitbit_data/nov08-nov21/|.csv","",nov08),".1",sep="")
    list2env(nov08_csv,envir=.GlobalEnv)
    rm(nov08,nov08_csv)
    
  # nov 22 - dec 05
    nov22<-list.files("fitbit_data/nov22-dec05", pattern="*.csv", full.names=TRUE)
    nov22_csv<-lapply(nov22, read.csv)
    names(nov22_csv)<-paste(gsub("fitbit_data/nov22-dec05/|.csv","",nov22),".2",sep="")
    list2env(nov22_csv,envir=.GlobalEnv)
    rm(nov22,nov22_csv)
  
  # dec 06 - dec 12
    dec06<-list.files("fitbit_data/dec06-dec12", pattern="*.csv", full.names=TRUE)
    dec06_csv<-lapply(dec06, read.csv)
    names(dec06_csv)<-paste(gsub("fitbit_data/dec06-dec12/|.csv","",dec06),".3",sep="")
    list2env(dec06_csv,envir=.GlobalEnv)
    rm(dec06,dec06_csv)
    
```

### for each unique data type/dataset, consolidate data from three time periods

```{r}

# generate list of unique datasets (there are 18)
    files<-unique(gsub("\\.1|\\.2|\\.3","",ls()))
    
  # for each unique type of data, rbind data from the three periods together
    for(i in 1:length(files)) {
      
      pattern<-files[i]
      X<-mget(ls(pattern=pattern)) %>% bind_rows()
      assign(gsub("_merged","",pattern),X)
      rm(list = ls()[grepl(pattern, ls())])
      rm(X)
      i<-i+1
      
    }
    
  # clean environment
    rm(i,pattern,files)
    
```

#### leaves a total of 18 unique dataframes

```{r}
    ls()
```

### (1) minute-level data: 

```{r}

      str(minuteStepsNarrow) # steps per minute
      str(minuteCaloriesNarrow) # calories burned each minute
      str(minuteIntensitiesNarrow) # intensity of activity during each minute -- 0, 1, 2 and 3
      str(minuteMETsNarrow) # MET value measued each minute
      str(heartrate_1min) # heart rate measured each minute -- fewer measurements than above
      str(`30secondSleepStages`) # sleep stages per 30 seconds? -- also fewer sleep observations
      str(minuteSleep) # sleep stage per minute?
      
```


